-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 14:35:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vgdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vgdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vgdb` DEFAULT CHARACTER SET utf8 ;
USE `vgdb` ;

-- -----------------------------------------------------
-- Table `vgdb`.`QuestionSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vgdb`.`QuestionSummary` (
  `idQuestionSummaries` INT NOT NULL,
  `ref` VARCHAR(80) NOT NULL,
  `voteCount` INT NOT NULL,
  `answerCount` INT NOT NULL,
  `viewCount` INT NOT NULL,
  `question` VARCHAR(500) NOT NULL,
  `tagCount` INT NOT NULL,
  `datePosted` DATETIME NOT NULL,
  PRIMARY KEY (`idQuestionSummaries`),
  INDEX `ref` (`ref` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vgdb`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vgdb`.`Tag` (
  `idTag` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB
PACK_KEYS = Default;


-- -----------------------------------------------------
-- Table `vgdb`.`AssocatedTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vgdb`.`AssocatedTag` (
  `idAssocatedTag` INT NOT NULL,
  `countDay` INT NULL,
  `countWeek` INT NULL,
  `countMonth` INT NULL,
  `countYear` INT NULL,
  `totalCount` INT NOT NULL,
  `tagId` INT NOT NULL,
  `questionSumaryId` INT NOT NULL,
  `dateScraped` DATETIME NOT NULL,
  PRIMARY KEY (`idAssocatedTag`),
  INDEX `questionSummary_idx` (`questionSumaryId` ASC) VISIBLE,
  INDEX `tagName_idx` (`tagId` ASC) VISIBLE,
  CONSTRAINT `tagName`
    FOREIGN KEY (`tagId`)
    REFERENCES `vgdb`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionSummary`
    FOREIGN KEY (`questionSumaryId`)
    REFERENCES `vgdb`.`QuestionSummary` (`idQuestionSummaries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
