-- MySQL Script generated by MySQL Workbench
-- Sun Dec 22 18:49:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vgdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vgdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vgdb` DEFAULT CHARACTER SET utf8 ;
USE `vgdb` ;

-- -----------------------------------------------------
-- Table `vgdb`.`QuestionSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vgdb`.`QuestionSummary` (
  `idQuestionSummary` INT NOT NULL AUTO_INCREMENT,
  `ref` VARCHAR(255) NOT NULL,
  `voteCount` INT NOT NULL,
  `answerCount` INT NOT NULL,
  `viewCount` INT NOT NULL,
  `question` VARCHAR(500) NOT NULL,
  `datePosted` DATETIME NOT NULL,
  `dateScraped` DATETIME NOT NULL,
  PRIMARY KEY (`idQuestionSummary`),
  INDEX `ref` (`ref` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vgdb`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vgdb`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `countDay` INT NULL,
  `countWeek` INT NULL,
  `countMonth` INT NULL,
  `countYear` INT NULL,
  `totalCount` INT NULL,
  `dateScraped` DATETIME NOT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB
PACK_KEYS = Default;


-- -----------------------------------------------------
-- Table `vgdb`.`AssociatedTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vgdb`.`AssociatedTag` (
  `idAssociatedTag` INT NOT NULL AUTO_INCREMENT,
  `tagId` INT NOT NULL,
  `questionSummaryId` INT NOT NULL,
  PRIMARY KEY (`idAssociatedTag`),
  INDEX `questionSummary_idx` (`questionSummaryId` ASC) VISIBLE,
  INDEX `tagName_idx` (`tagId` ASC) VISIBLE,
  CONSTRAINT `tagName`
    FOREIGN KEY (`tagId`)
    REFERENCES `vgdb`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionSummary`
    FOREIGN KEY (`questionSummaryId`)
    REFERENCES `vgdb`.`QuestionSummary` (`idQuestionSummary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vgdb`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vgdb`.`Article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `abstract` VARCHAR(5000) NULL,
  `webUrl` VARCHAR(150) NOT NULL,
  `snippet` VARCHAR(500) NULL,
  `leadParagraph` VARCHAR(5000) NULL,
  `printSection` VARCHAR(45) NULL,
  `printPage` VARCHAR(45) NULL,
  `sourceName` VARCHAR(45) NOT NULL,
  `headline` VARCHAR(45) NULL,
  `pubDate` DATETIME NOT NULL,
  `documentType` VARCHAR(45) NULL,
  `sectionName` VARCHAR(45) NULL,
  `id` VARCHAR(150) NOT NULL,
  `dateScraped` DATETIME NOT NULL,
  PRIMARY KEY (`idArticle`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vgdb`.`AssociatedArticle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vgdb`.`AssociatedArticle` (
  `idAssociatedArticle` INT NOT NULL AUTO_INCREMENT,
  `articleId` INT NOT NULL,
  `questionSummaryId` INT NOT NULL,
  `score` DECIMAL(5,4) NULL,
  PRIMARY KEY (`idAssociatedArticle`),
  INDEX `questionSummaryId_idx` (`questionSummaryId` ASC) VISIBLE,
  INDEX `articleId_idx` (`articleId` ASC) VISIBLE,
  CONSTRAINT `questionSummaryId`
    FOREIGN KEY (`questionSummaryId`)
    REFERENCES `vgdb`.`QuestionSummary` (`idQuestionSummary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articleId`
    FOREIGN KEY (`articleId`)
    REFERENCES `vgdb`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
